[settings]
pipx.uvx = true
python.uv_venv_auto = true

[tools]
"pipx:dotbot" = "latest"
task = "latest"
uv = "latest"
bun = "latest"
pnpm = "latest"
"github:pkgxdev/pkgx" = { version = "latest", os = ["windows"] }
"github:marwanhawari/stew" = { version = "latest", os = ["windows"] }
"github:dyoshikawa/rulesync" = "latest"
