entrypoint: brew
command: install

run:
  - { args: util-linux }
  - { args: util-macros }
  - { args: coreutils }
  - { args: diffutils }
  - { args: findutils }
  - { args: uutils-coreutils }
  - { args: uutils-diffutils }
  - { args: uutils-findutils }
  - { args: binutils }
  - { args: dateutils }
  - { args: inetutils }
  - { args: iputils }
  - { args: mailutils }
  - { args: moreutils }
  - { args: nfcutils }
  - { args: pciutils }
  - { args: plotutils }
  - { args: recutils }
  - { args: usbutils }
