entrypoint: kubectl
command: "krew install"

run:
  - { args: oidc-login }
  - { args: access-matrix }
  - { args: cert-manager }
  - { args: cilium }
  - { args: cnpg }
  - { args: cost }
  - { args: explore }
  - { args: flame }
  - { args: kc }
  - { args: pv-migrate }
  - { args: stern }
  - { args: tree }
  - { args: vela }
