presets:
  scoop-install:
    entrypoint: scoop
    command: install

groups:
  accounting:
  - { preset: scoop-install, args: gnucash }
  # - { preset: scoop-install, args: moneymanagerex}

  book:
  # - { preset: scoop-install, args: calibre-web}
  # - { preset: scoop-install, args: calibre}

  text:
  - { preset: scoop-install, args: grex }
  - { preset: scoop-install, args: ripgrep }
  # - { preset: scoop-install, args: sig}
  - { preset: scoop-install, args: ugrep }
  # - { preset: scoop-install, args: gdm257/shim-grep}
  - { preset: scoop-install, args: ag }
  # - { preset: scoop-install, args: ack}
  - { preset: scoop-install, args: main/sd }
  # - { preset: scoop-install, args: sad}
  # - { preset: scoop-install, args: ruplacer}
  - { preset: scoop-install, args: bat }
  # - { preset: scoop-install, args: miller}
  # - { preset: scoop-install, args: tailspin}
  # - { preset: scoop-install, args: logdy}
  - { preset: scoop-install, args: sttr }

  json:
  # - { preset: scoop-install, args: fx}
  # - { preset: scoop-install, args: jid}
  # - { preset: scoop-install, args: csview}
  - { preset: scoop-install, args: jq }
  # - { preset: scoop-install, args: xq}
  - { preset: scoop-install, args: yq }
  # - { preset: scoop-install, args: fq}
  # - { preset: scoop-install, args: dasel}
  - { preset: scoop-install, args: xidel }
  # - { preset: scoop-install, args: pup}

  spreadsheet:
  - { preset: scoop-install, args: csvlens }
  # - { preset: scoop-install, args: dsq}
  # - { preset: scoop-install, args: q}
  - { preset: scoop-install, args: sq }

  openapi:
  # - { preset: scoop-install, args: openapi-tui}

  - { preset: scoop-install, args: hashcat }
  - { preset: scoop-install, args: john-the-ripper }
  - { preset: scoop-install, args: 7z2hashcat }

  doc:
  - { preset: scoop-install, args: pandoc }
  - { preset: scoop-install, args: main/officecli }
  - { preset: scoop-install, args: poppler }
  # - { preset: scoop-install, args: vosviewer}
  - { preset: scoop-install, args: lfs/awesome-books }
  # - { preset: scoop-install, args: zeal}
  # - { preset: scoop-install, args: koodo-reader}
  # - { preset: scoop-install, args: "mendeley mendeley-desktop"}

  dict:
  - { preset: scoop-install, args: eudic -s }
  - { preset: scoop-install, args: gdm257/awesome-dict }
  # - { preset: scoop-install, args: ting-en}
  # - { preset: scoop-install, args: anki}
  # - { preset: scoop-install, args: goldendict-ng}

  clipboard:
  - { preset: scoop-install, args: ditto }
  # - { preset: scoop-install, args: gdm257/ecopastepro}
  # - { preset: scoop-install, args: ecopaste}
  # - { preset: scoop-install, args: copyq}
  # - { preset: scoop-install, args: clipboard}

  note:
  # - { preset: scoop-install, args: zotero}
  # - { preset: scoop-install, args: anytype}
  - { preset: scoop-install, args: obsidian }
  # - { preset: scoop-install, args: tolaria}
  # - { preset: scoop-install, args: siyuan}
  # - { preset: scoop-install, args: focalboard}
  # - { preset: scoop-install, args: appflowy}
  # - { preset: scoop-install, args: speedynote}
  # - { preset: scoop-install, args: bookxnote}
  - { preset: scoop-install, args: BookXNotePro }
  # - { preset: scoop-install, args: xournalpp}
  # - { preset: scoop-install, args: rendevoz}
  # - { preset: scoop-install, args: logseq}

  ime:
  # - { preset: scoop-install, args: imewlconverter}
  - { preset: scoop-install, args: gdm257/windinput }

  markdown:
  # - { preset: scoop-install, args: zettlr}
  # - { preset: scoop-install, args: typora}
  # - { preset: scoop-install, args: marktext}
  # - { preset: scoop-install, args: gdm257/md-preview}
  - { preset: scoop-install, args: gdm257/inknote }
  # - { preset: scoop-install, args: gdm257/vividmark}
  # - { preset: scoop-install, args: gdm257/markview}

  tex:
  # - { preset: scoop-install, args: texlive}
  # - { preset: scoop-install, args: latex}

  text-editor:
  # - { preset: scoop-install, args: zed}
  # - { preset: scoop-install, args: zed-opengl}
  # - { preset: scoop-install, args: notepad4}
  # - { preset: scoop-install, args: notepad--}
  # - { preset: scoop-install, args: notepadnext}
  # - { preset: scoop-install, args: notepadplusplus}
  # - { preset: scoop-install, args: islide}
  # - { preset: scoop-install, args: vscode-portable}
  - { preset: scoop-install, args: emeditor }
  # - { preset: scoop-install, args: sublime-text}
  # - { preset: scoop-install, args: notepad2-mod}
  # - { preset: scoop-install, args: notepad3}
  # - { preset: scoop-install, args: geany}

  pdf-cli:
  - { preset: scoop-install, args: pdftk }

  pdf-viewer:
  # - { preset: scoop-install, args: SumatraPDF_dodorz }
  - { preset: scoop-install, args: sumatrapdf-stable }

  pdf-editor:
  - { preset: scoop-install, args: gdm257/pdfcraft }
  # - { preset: scoop-install, args: gdm257/killerpdf }
  # - { preset: scoop-install, args: pdf-xchange-editor}
  # - { preset: scoop-install, args: pdfpatcher_hu3rror}
  # - { preset: scoop-install, args: pdfpatcher}
  # - { preset: scoop-install, args: pdf-guru}

  font:
  - { preset: scoop-install, args: fontforge }
  - { preset: scoop-install, args: winfontsview }

  read-it-later:
  # - { preset: scoop-install, args: raindrop.io}

  office:
  # - { preset: scoop-install, args: libreoffice}
  - { preset: scoop-install, args: gdm257/wordcraft }
  - { preset: scoop-install, args: gdm257/gridcraft }
  - { preset: scoop-install, args: gdm257/deckcraft }

  rss:
  - { preset: scoop-install, args: rssguard }
  # - { preset: scoop-install, args: fluent-reader}


run:
  - { group: accounting }
  - { group: book }
  - { group: text }
  - { group: json }
  - { group: spreadsheet }
  - { group: openapi }
  - { group: doc }
  - { group: dict }
  - { group: clipboard }
  - { group: note }
  - { group: ime }
  - { group: markdown }
  - { group: tex }
  - { group: text-editor }
  - { group: pdf-cli }
  - { group: pdf-viewer }
  - { group: pdf-editor }
  - { group: font }
  - { group: read-it-later }
  - { group: office }
  - { group: rss }
