presets:
  scoop-install:
    entrypoint: scoop
    command: install

groups:
  pe:
  - { preset: scoop-install, args: ventoy }
  # - { preset: scoop-install, args: wepe}
  - { preset: scoop-install, args: rufus }
  - { preset: scoop-install, args: balenaEtcher-Portable }
  # - { preset: scoop-install, args: unetbootin}

  vm:
  - { preset: scoop-install, args: virtualbox-extension }
  - { preset: scoop-install, args: lxrunoffline }
  - { preset: scoop-install, args: packer }
  - { preset: scoop-install, args: vagrant }
  - { preset: scoop-install, args: qemu }
  # - { preset: scoop-install, args: wsl2host}
  # - { preset: scoop-install, args: virtualbox-with-extension-pack-np}
  # - { preset: scoop-install, args: virtualbox-with-extension-pack-np_ScoopInstaller}
  # - { preset: scoop-install, args: WSABuildsWindows10}
  # - { preset: scoop-install, args: WSABuildsWindows11}
  # - { preset: scoop-install, args: wsl-centos-7}
  # - { preset: scoop-install, args: wsl-centos-8}
  # - { preset: scoop-install, args: nixos-wsl}
  # - { preset: scoop-install, args: wsl2-distro-manager}
  - { preset: scoop-install, args: wsl-dashboard }
  # - { preset: scoop-install, args: WsaToolbox}
  # - { preset: scoop-install, args: wsldl}

  emulator:
  - { preset: scoop-install, args: gdm257/EmuDeck }
  # - { preset: scoop-install, args: pegasus}
  # - { preset: scoop-install, args: cemu-dev}
  # - { preset: scoop-install, args: xemu}
  # - { preset: scoop-install, args: yuzu}
  # - { preset: scoop-install, args: azahar}
  # - { preset: scoop-install, args: citra-nightly}
  # - { preset: scoop-install, args: citra}
  # - { preset: scoop-install, args: dolphin-dev}
  # - { preset: scoop-install, args: duckstation}
  # - { preset: scoop-install, args: flycast}
  # - { preset: scoop-install, args: mgba}
  # - { preset: scoop-install, args: melonDS}
  # - { preset: scoop-install, args: mame}
  # - { preset: scoop-install, args: ppsspp}
  # - { preset: scoop-install, args: pcsx2}
  # - { preset: scoop-install, args: rpcs3}
  # - { preset: scoop-install, args: ryujinx}
  # - { preset: scoop-install, args: retroarch}
  # - { preset: scoop-install, args: vita3k}
  # - { preset: scoop-install, args: shadps4}
  # - { preset: scoop-install, args: supermodel}
  # - { preset: scoop-install, args: ScummVM}
  # - { preset: scoop-install, args: xenia}
  - { preset: scoop-install, args: LDPlayer-Portable }
  - { preset: scoop-install, args: onscripteryuri }
  - { preset: scoop-install, args: onscripter-w }
  - { preset: scoop-install, args: onscripter-jh }
  - { preset: scoop-install, args: onscripter-ru }
  - { preset: scoop-install, args: ruffle-nightly }

  # container
  - { preset: scoop-install, args: docker }
  # - { preset: scoop-install, args: docker-compose}
  - { preset: scoop-install, args: lazydocker }
  - { preset: scoop-install, args: gdm257/lazywslc }
  - { preset: scoop-install, args: ctop }
  # - { preset: scoop-install, args: dockle}
  # - { preset: scoop-install, args: diun}
  # - { preset: scoop-install, args: hadolint}
  # - { preset: scoop-install, args: dive}
  # - { preset: scoop-install, args: portainer}
  - { preset: scoop-install, args: nixpacks }
  - { preset: scoop-install, args: kompose }
  # - { preset: scoop-install, args: kustomize}
  - { preset: scoop-install, args: helm }
  - { preset: scoop-install, args: helmfile }
  # - { preset: scoop-install, args: kcl}
  # - { preset: scoop-install, args: autok3s}
  # - { preset: scoop-install, args: k3sup}
  # - { preset: scoop-install, args: k3d}
  # - { preset: scoop-install, args: rancher-desktop}
  # - { preset: scoop-install, args: minikube}
  # - { preset: scoop-install, args: kind}
  # - { preset: scoop-install, args: kubeadm}
  - { preset: scoop-install, args: openlens }
  # - { preset: scoop-install, args: lens}
  # - { preset: scoop-install, args: headlamp}
  # - { preset: scoop-install, args: seabird}
  - { preset: scoop-install, args: kdash }
  - { preset: scoop-install, args: k9s }
  - { preset: scoop-install, args: kubectl }
  - { preset: scoop-install, args: krew }
  - { preset: scoop-install, args: kubens }
  - { preset: scoop-install, args: kubectx }
  # - { preset: scoop-install, args: kubecolor}
  # - { preset: scoop-install, args: kubectl-ai}
  # - { preset: scoop-install, args: kubeconform}
  # - { preset: scoop-install, args: k8sgpt}
  - { preset: scoop-install, args: kubevpn }
  # - { preset: scoop-install, args: cilium-cli}
  # - { preset: scoop-install, args: istioctl}
  # - { preset: scoop-install, args: kwok}
  # - { preset: scoop-install, args: kubeshark}
  # - { preset: scoop-install, args: kops}
  # - { preset: scoop-install, args: main/flux}
  # - { preset: scoop-install, args: argocd}
  # - { preset: scoop-install, args: argocd-autopilot}
  # - { preset: scoop-install, args: tsuru}
  # - { preset: scoop-install, args: velero}
  # - { preset: scoop-install, args: cmctl}
  # - { preset: scoop-install, args: korb}
  # - { preset: scoop-install, args: sandboxie-plus-np}
  - { preset: scoop-install, args: devpod }


run:
  - { group: pe }
  - { group: vm }
  - { group: emulator }
