presets:
  scoop-config:
    entrypoint: scoop
    command: config

run:
  - { preset: scoop-config, args: "aria2-enabled true"}
  - { preset: scoop-config, args: "debug true"}
  - { preset: scoop-config, args: "use_sqlite_cache true"}
  - { preset: scoop-config, args: "use_lessmsi true"}
