# yaml-language-server: $schema=https://raw.githubusercontent.com/runkids/skillshare/main/schemas/config.schema.json
source: ~\AppData\Roaming\skillshare\skills
agents_source: ~/AppData/Roaming/skillshare/agents
extras_source: ~/AppData/Roaming/skillshare/extras
targets:
  claude:
    skills:
      mode: copy
    agents:
      mode: copy
  opencode:
    skills:
      exclude:
        - '*'
    agents:
      mode: copy
  universal:
    skills:
      mode: copy
extras:
  - name: codex-agents
    source: ~/AppData/Roaming/skillshare/agents
    targets:
      - path: ~/.codex/agents
        extension: codex-agents
  - name: rules
    # source: ~/AppData/Roaming/skillshare/extras/rules
    targets:
      - path: ~/AppData/Roaming/skillshare/extensions/ruler/dummy
        extension: ruler
ignore:
  - '**/.DS_Store'
  - '**/.git/**'
audit:
  block_threshold: CRITICAL
