[settings]
trusted_config_paths = ["/"]
experimental = true
env_file = ".env"
env_shell_expand = true
jobs = 4
github.use_git_credentials = true
prefer_offline = true
minimum_release_age = "1h"
auto_install = false
exec_auto_install = true
npm.package_manager = "bun"
pipx.uvx = true
python.uv_venv_auto = true

[tools]
"npm:@fission-ai/openspec" = { version = "latest", os = ["windows"] }

"pipx:git+https://github.com/SilentSnowSoul/tachibk-converter.git" = { version = "main", os = ["windows"] }
"pipx:git+https://github.com/SilentSnowSoul/magnetizer.git" = { version = "main", os = ["windows"] }
"pipx:httpie" = { version = "latest", os = ["windows"] }
"pipx:marimo" = { version = "latest", extras = "recommended", os = ["windows"] }
"pipx:ptpython" = { version = "latest", os = ["windows"] }
"pipx:pyright" = { version = "latest", os = ["windows"] }
"pipx:browser-harness" = { version = "latest", os = ["windows"] }
