[settings]
trusted_config_paths = ["/"]
experimental = true
env_file = ".env"
env_shell_expand = true
jobs = 4
github.use_git_credentials = true
prefer_offline = true
npm.package_manager = "pnpm" # npm, pnpm, bun (require mise 2025.12.7+)
pipx.uvx = true
python.uv_venv_auto = true

[tools]
bun = "latest"
node = { version = "lts", postinstall = "corepack enable" }
dart = "latest"
pnpm = "latest"
uv = "latest"
"github:pkgxdev/pkgx" = "latest"
"github:marwanhawari/stew" = "latest"
task = "latest"
yazi = "latest"
zellij = { version = "latest", os = ["linux", "macos"] }

"dotnet:dotnet-repl" = "latest"
"dotnet:Microsoft.dotnet-interactive" = "latest"
"dotnet:csharp-ls" = "latest"

"cargo:binsider" = { version = "latest", os = ["linux", "macos"] }

"go:golang.org/x/tools/gopls" = "v0.21.0"

"npm:neoss" = { version = "latest", os = ["linux"] }
"npm:@openacp/cli" = "latest"
"npm:@mindfoldhq/trellis" = "beta"
"npm:@fission-ai/openspec" = "latest"
"npm:@agentmemory/agentmemory" = { version = "latest", postinstall = "agentmemory connect claude-code --with-hooks" }

"pipx:isd" = { version = "latest", os = ["linux", "macos"] }
"pipx:git+https://github.com/gdm257/magnetizer.git" = "main"
"pipx:fonttools" = { version = "latest", extras = "ufo,lxml,woff,unicode" }
"pipx:httpie" = "latest"
"pipx:marimo" = { version = "latest", extras = "recommended" }
"pipx:ptpython" = "latest"
"pipx:pyright" = "latest"
"pipx:semble" = "latest"
"pipx:code-review-graph" = "latest"
