[settings]
trusted_config_paths = ["/"]
experimental = true
env_file = ".env"
env_shell_expand = true
jobs = 4
github.use_git_credentials = true
prefer_offline = true
auto_install = false
exec_auto_install = true
npm.package_manager = "pnpm"
pipx.uvx = true
python.uv_venv_auto = true

[tools]
bun = { version = "latest", os = ["windows"] }
node = { version = "lts", postinstall = "corepack enable", os = ["windows"] }
dart = { version = "latest", os = ["windows"] }
pnpm = { version = "latest", os = ["windows"] }
uv = { version = "latest", os = ["windows"] }
"github:pkgxdev/pkgx" = { version = "latest", os = ["windows"] }
"github:marwanhawari/stew" = { version = "latest", os = ["windows"] }
task = { version = "latest", os = ["windows"] }
yazi = { version = "latest", os = ["windows"] }
zellij = { version = "latest", os = ["linux", "macos"] }

"dotnet:dotnet-repl" = { version = "latest", os = ["windows"] }
"dotnet:Microsoft.dotnet-interactive" = { version = "latest", os = ["windows"] }
"dotnet:csharp-ls" = { version = "latest", os = ["windows"] }

"cargo:binsider" = { version = "latest", os = ["linux", "macos"] }

"go:golang.org/x/tools/gopls" = { version = "v0.21.0", os = ["windows"] }

"npm:neoss" = { version = "latest", os = ["linux"] }
"npm:@openacp/cli" = { version = "latest", os = ["windows"] }
"npm:@intellectronica/ruler" = { version = "latest", os = ["windows"] }
"npm:@fission-ai/openspec" = { version = "latest", os = ["windows"] }
"npm:@mindfoldhq/trellis" = { version = "latest", os = ["windows"] }

"pipx:isd" = { version = "latest", os = ["linux", "macos"] }
"pipx:git+https://github.com/SilentSnowSoul/tachibk-converter.git" = { version = "main", os = ["windows"] }
"pipx:git+https://github.com/SilentSnowSoul/magnetizer.git" = { version = "main", os = ["windows"] }
"pipx:fonttools" = { version = "latest", extras = "ufo,lxml,woff,unicode", os = ["windows"] }
"pipx:httpie" = { version = "latest", os = ["windows"] }
"pipx:marimo" = { version = "latest", extras = "recommended", os = ["windows"] }
"pipx:ptpython" = { version = "latest", os = ["windows"] }
"pipx:pyright" = { version = "latest", os = ["windows"] }
"pipx:browser-harness" = { version = "latest", extras = "mcp", os = ["windows"] }
"pipx:semble" = { version = "latest", extras = "mcp", os = ["windows"] }
"pipx:litellm" = { version = "latest", extras = "proxy", os = ["windows"] }
