entrypoint: brew
command: install

run:
  # === vps ===
  - {args: go-task}
  - {args: just}
  - {args: make}
  - {args: cmake}
  - {args: vfox}
  - {args: gcc}
  - {args: llvm}
  - {args: go}
  - {args: micromamba}
  - {args: rust}
  - {args: volta}
  - {args: git}
  - {args: gitui}
  - {args: lazygit}
  # === devops ===
  - {args: go-task}
  - {args: just}
  - {args: make}
  - {args: cmake}
  - {args: vfox}
  - {args: asdf}
  - {args: whalebrew}
  - {args: croc}
  - {args: eget}
  - {args: apt}
  - {args: dpkg}
  - {args: volta}
  # - {args: pipx}
  # - {args: rye}
  - {args: micromamba}
  - {args: ruff}
  - {args: gradle}
  - {args: adb-enhanced}
  - {args: apktool}
  - {args: nuget}
  - {args: gcc}
  - {args: llvm}
  - {args: xmake}
  - {args: conan}
  - {args: gdb}
  - {args: upx}
  - {args: doxygen}
  - {args: shellcheck}
  - {args: shfmt}
  - {args: luajit}
  - {args: luarocks}
  # - {args: "lua@5.3"}
  - {args: go}
  - {args: golangci-lint}
  - {args: goreleaser}
  - {args: protoc-gen-go}
  - {args: gf}
  - {args: rust}
  # - {args: rustup}
  - {args: perl}
  # PHP
  # - {args: "php@8.2"}
  - {args: "shivammathur/php/php@8.2"}
  # PHP extensions
  - {args: "shivammathur/extensions/xdebug@8.2"}
  # === downloader ===
  - {args: chsrc}
  - {args: rclone}
  - {args: restic}
  - {args: rsync}
  - {args: lrzsz}
  # === file ===
  - {args: file-formula}
  - {args: unar}
  - {args: unzip}
  - {args: gnu-tar}
  - {args: 7zip}
  - {args: age}
  - {args: ncdu}
  - {args: tre}
  - {args: duf}
  - {args: dust}
  - {args: yazi}
  - {args: superfile}
  - {args: eza}
  - {args: fzf}
  - {args: fd}
  - {args: lsof}
  - {args: rename}
  - {args: trash}
  # === kernel ===
  - {args: cyme}
  - {args: tz}
  - {args: fastfetch}
  # === layer ===
  - {args: qemu}
  - {args: nemu}
  - {args: docker}
  - {args: docker-compose}
  - {args: docker-buildx}
  - {args: lazydocker}
  - {args: ctop}
  - {args: dive}
  - {args: kompose}
  - {args: kustomize}
  - {args: helm}
  - {args: helmfile}
  - {args: "kcl-lang/tap/kcl"}
  - {args: k3sup}
  - {args: "kdash-rs/kdash/kdash"}
  - {args: k9s}
  - {args: kubernetes-cli}
  - {args: krew}
  - {args: kubectx}
  # - {args: nomad}
  # - {args: "robinovitch61/tap/wander"}
  # - {args: "dokku/repo/dokku"}
  # === network ===
  - {args: curl}
  - {args: wget}
  - {args: nftables}
  - {args: iptables}
  - {args: iproute2}
  - {args: net-tools}
  - {args: iputils}
  - {args: gping}
  # - {args: dog}
  - {args: doggo}
  - {args: asn}
  - {args: curlie}
  - {args: websocat}
  - {args: mkcert}
  - {args: bitwarden-cli}
  - {args: bandwhich}
  - {args: nethogs}
  - {args: iftop}
  - {args: iotop}
  - {args: iperf3}
  - {args: tcpdump}
  - {args: "guumaster/tap/hostctl"}
  # === process ===
  - {args: systemd}
  - {args: htop}
  - {args: bottom}
  - {args: pstree}
  - {args: procs}
  # === shell ===
  - {args: zsh}
  - {args: "powershell/tap/powershell"}
  # - {args: "powershell/tap/powershell-lts"}
  - {args: openssh}
  - {args: trzsz-ssh}
  - {args: mosh}
  # - {args: screen}
  # - {args: tmux}
  - {args: zellij}
  - {args: asciinema}
  - {args: atuin}
  - {args: clipboard}
  - {args: mcfly}
  - {args: tealdeer}
  # - {args: wtfutil}
  - {args: zoxide}
  - {args: rargs}
  - {args: "dotenvx/brew/dotenvx"}
  # === text ===
  - {args: vim}
  - {args: neovim}
  # - {args: amp}
  - {args: bat}
  - {args: mdcat}
  - {args: sad}
  - {args: yq}
  - {args: ag}
  - {args: ripgrep}
  - {args: ugrep}
  - {args: grex}
  - {args: grep}
  - {args: gnu-sed}
  - {args: awk}
  - {args: fnt}
  - {args: argon2}
  - {args: less}
  # === toolbox ===
  - {args: util-linux}
  - {args: util-macros}
  - {args: coreutils}
  - {args: diffutils}
  - {args: findutils}
  - {args: uutils-coreutils}
  - {args: uutils-diffutils}
  - {args: uutils-findutils}
  - {args: binutils}
  - {args: dateutils}
  - {args: inetutils}
  - {args: iputils}
  - {args: mailutils}
  - {args: moreutils}
  - {args: nfcutils}
  - {args: pciutils}
  - {args: plotutils}
  - {args: recutils}
  - {args: usbutils}
  # === video ===
  - {args: ffmpeg}
